
#r"../packages/FSharp.Data.Xsd.0.0.7/lib/net45/FSharp.Data.Xsd.dll"
#r"System.Xml"
#r"System.Xml.Linq"

open FSharp.Data


//type t1 = XmlProvider<Schema ="gpx.xsd", ResolutionFolder="""c:\temp\schemas""">
//type t2 = XmlProvider<Schema ="ImportCreditRegistry_v.3.xsd", ResolutionFolder="""c:\temp\schemas""">
//type t3 = XmlProvider<Schema ="po.xsd", ResolutionFolder="""c:\temp\schemas""">
//type t4 = XmlProvider<Schema ="xmlopts.xsd", ResolutionFolder="""c:\temp\schemas\altova\files""">
//type t5 = XmlProvider<Schema ="config.xsd", ResolutionFolder="""c:\temp\schemas\altova\files\raptorxml""">
//type t7 = XmlProvider<Schema ="parameters.xsd", ResolutionFolder="""c:\temp\schemas\altova\files\raptorxml""">
//type t8 = XmlProvider<Schema ="cmlCore.xsd", ResolutionFolder="""c:\temp\schemas\cml\files""">
//type t47 = XmlProvider<Schema ="container.xsd", ResolutionFolder="""c:\temp\schemas\epub\files""">
//type t48 = XmlProvider<Schema ="opf.xsd", ResolutionFolder="""c:\temp\schemas\epub\files""">
//type t49 = XmlProvider<Schema ="opf2.xsd", ResolutionFolder="""c:\temp\schemas\epub\files""">
//type t50 = XmlProvider<Schema ="ApplicationAcknowledgement.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t51 = XmlProvider<Schema ="AssessmentCancelRequest.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t52 = XmlProvider<Schema ="AssessmentCatalog.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t53 = XmlProvider<Schema ="AssessmentCatalogQuery.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t54 = XmlProvider<Schema ="AssessmentOrderAcknowledgement.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t55 = XmlProvider<Schema ="AssessmentOrderRequest.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t56 = XmlProvider<Schema ="AssessmentResult.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t57 = XmlProvider<Schema ="AssessmentStatusRequest.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t58 = XmlProvider<Schema ="Assignment.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t59 = XmlProvider<Schema ="BackgroundCheck.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t60 = XmlProvider<Schema ="BackgroundCheckStatusRequest.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t61 = XmlProvider<Schema ="BackgroundReports.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t62 = XmlProvider<Schema ="Candidate.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t63 = XmlProvider<Schema ="Credit.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t64 = XmlProvider<Schema ="CustomerReportingRequirements.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t65 = XmlProvider<Schema ="Enrollment.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t66 = XmlProvider<Schema ="EPMDevelopmentPlan.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t67 = XmlProvider<Schema ="EPMObjectivesPlan.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t68 = XmlProvider<Schema ="EPMObjectivesResult.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t69 = XmlProvider<Schema ="EPMRemunerationResult.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t70 = XmlProvider<Schema ="EPMResult.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t71 = XmlProvider<Schema ="EPMSummaryResult.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t72 = XmlProvider<Schema ="ExerciseConfirmation.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t73 = XmlProvider<Schema ="ExerciseRequest.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t74 = XmlProvider<Schema ="Grant.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t75 = XmlProvider<Schema ="HumanResource.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t76 = XmlProvider<Schema ="IndicativeBatch.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t77 = XmlProvider<Schema ="IndicativeData.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t78 = XmlProvider<Schema ="Invoice.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t79 = XmlProvider<Schema ="MetricsInterchange.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t80 = XmlProvider<Schema ="NewHire.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t81 = XmlProvider<Schema ="PayrollBenefitContributions.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t82 = XmlProvider<Schema ="PayrollInstructions.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t83 = XmlProvider<Schema ="PositionOpening.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t84 = XmlProvider<Schema ="Rates.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t85 = XmlProvider<Schema ="RemoveExerciseConfirmations.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t86 = XmlProvider<Schema ="RemoveExerciseRequests.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t87 = XmlProvider<Schema ="RemoveGrants.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t88 = XmlProvider<Schema ="RemoveStockDeposits.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t89 = XmlProvider<Schema ="RemoveStockPlanParticipants.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t90 = XmlProvider<Schema ="RemoveStockPlans.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t91 = XmlProvider<Schema ="RemoveStockSaleConfirmations.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t92 = XmlProvider<Schema ="ResourceScreening.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t93 = XmlProvider<Schema ="Resume.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t94 = XmlProvider<Schema ="simpledc20021212.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t95 = XmlProvider<Schema ="StaffingAction.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t96 = XmlProvider<Schema ="StaffingOrder.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t97 = XmlProvider<Schema ="StaffingOrganization.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t98 = XmlProvider<Schema ="StaffingPosition.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t99 = XmlProvider<Schema ="StaffingShift.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t100 = XmlProvider<Schema ="StockDeposit.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t101 = XmlProvider<Schema ="StockPlan.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t102 = XmlProvider<Schema ="StockPlanParticipant.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t103 = XmlProvider<Schema ="StockPurchasePlanCoverage.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t104 = XmlProvider<Schema ="StockSaleConfirmation.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t105 = XmlProvider<Schema ="TimeCard.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t106 = XmlProvider<Schema ="TimeCardConfiguration.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t108 = XmlProvider<Schema ="xmldsig-core-schema.xsd", ResolutionFolder="""c:\temp\schemas\hr-xml""">
//type t109 = XmlProvider<Schema ="mathml2.xsd", ResolutionFolder="""c:\temp\schemas\math\files""">
//type t129 = XmlProvider<Schema ="characters.xsd", ResolutionFolder="""c:\temp\schemas\math\files\presentation""">
//type t143 = XmlProvider<Schema ="mathml3.xsd", ResolutionFolder="""c:\temp\schemas\mathml3\files""">
//type t144 = XmlProvider<Schema ="DeliveryOrder_NCA_V1R1.xsd", ResolutionFolder="""c:\temp\schemas\NCAXML""">
//type t145 = XmlProvider<Schema ="Invoice_NCA_V1R1.xsd", ResolutionFolder="""c:\temp\schemas\NCAXML""">
//type t146 = XmlProvider<Schema ="SampleOrder_NCA_V1R1.xsd", ResolutionFolder="""c:\temp\schemas\NCAXML""">
//type t147 = XmlProvider<Schema ="ShippingAdvice_NCA_V1R1.xsd", ResolutionFolder="""c:\temp\schemas\NCAXML""">
//type t148 = XmlProvider<Schema ="nitf-3-4-ruby-include.xsd", ResolutionFolder="""c:\temp\schemas\NITF\files""">
//type t149 = XmlProvider<Schema ="nitf-3-4.xsd", ResolutionFolder="""c:\temp\schemas\NITF\files""">
//type t150 = XmlProvider<Schema ="P3Pv1.xsd", ResolutionFolder="""c:\temp\schemas\p3p\files""">
//type t153 = XmlProvider<Schema ="RIXML-2_2.xsd", ResolutionFolder="""c:\temp\schemas\rixml""">
//type t154 = XmlProvider<Schema ="RIXML-Common-2_2.xsd", ResolutionFolder="""c:\temp\schemas\rixml""">
//type t159 = XmlProvider<Schema ="UBL-CommonAggregateComponents-2.1.xsd", ResolutionFolder="""c:\temp\schemas\UBL\files\common""">
//type t160 = XmlProvider<Schema ="UBL-CommonBasicComponents-2.1.xsd", ResolutionFolder="""c:\temp\schemas\UBL\files\common""">
//type t167 = XmlProvider<Schema ="UBL-SignatureBasicComponents-2.1.xsd", ResolutionFolder="""c:\temp\schemas\UBL\files\common""">
//type t237 = XmlProvider<Schema ="grammar-core.xsd", ResolutionFolder="""c:\temp\schemas\voicexml\files""">
//type t238 = XmlProvider<Schema ="grammar.xsd", ResolutionFolder="""c:\temp\schemas\voicexml\files""">
//type t239 = XmlProvider<Schema ="synthesis-core.xsd", ResolutionFolder="""c:\temp\schemas\voicexml\files""">
//type t240 = XmlProvider<Schema ="synthesis.xsd", ResolutionFolder="""c:\temp\schemas\voicexml\files""">
//type t243 = XmlProvider<Schema ="vxml-grammar-extension.xsd", ResolutionFolder="""c:\temp\schemas\voicexml\files""">
//type t244 = XmlProvider<Schema ="vxml-grammar-restriction.xsd", ResolutionFolder="""c:\temp\schemas\voicexml\files""">
//type t246 = XmlProvider<Schema ="vxml-synthesis-restriction.xsd", ResolutionFolder="""c:\temp\schemas\voicexml\files""">
//type t247 = XmlProvider<Schema ="vxml.xsd", ResolutionFolder="""c:\temp\schemas\voicexml\files""">
//type t248 = XmlProvider<Schema ="encoding.xsd", ResolutionFolder="""c:\temp\schemas\wsdl\files""">
//type t249 = XmlProvider<Schema ="envelope.xsd", ResolutionFolder="""c:\temp\schemas\wsdl\files""">
//type t252 = XmlProvider<Schema ="soap-envelope.xsd", ResolutionFolder="""c:\temp\schemas\wsdl\files""">
//type t254 = XmlProvider<Schema ="wsdl.xsd", ResolutionFolder="""c:\temp\schemas\wsdl\files""">
//type t261 = XmlProvider<Schema ="xlink.xsd", ResolutionFolder="""c:\temp\schemas\xlink\files""">
//type t262 = XmlProvider<Schema ="xlink11.xsd", ResolutionFolder="""c:\temp\schemas\xlink\files""">
//type t264 = XmlProvider<Schema ="xlink.xsd", ResolutionFolder="""c:\temp\schemas\xmlspec\files""">
//type t265 = XmlProvider<Schema ="xml.xsd", ResolutionFolder="""c:\temp\schemas\xmlspec\files""">
//type t266 = XmlProvider<Schema ="xmlspec.xsd", ResolutionFolder="""c:\temp\schemas\xmlspec\files""">
//type t267 = XmlProvider<Schema ="analyze-string.xsd", ResolutionFolder="""c:\temp\schemas\xpath\files""">
//type t268 = XmlProvider<Schema ="schema-for-serialization-parameters.xsd", ResolutionFolder="""c:\temp\schemas\xpath\files""">
//type t269 = XmlProvider<Schema ="schema_for_serialization_parameters.xsd", ResolutionFolder="""c:\temp\schemas\xquery\files""">
//type t275 = XmlProvider<Schema ="xsl_fo.xsd", ResolutionFolder="""c:\temp\schemas\xsl\files""">
